### ISSUE TITLE
Alerts count counts other tabs than "Open"

### ISSUE THREAD

**Issue by noahadhikari** [Berkeley-CS61B/simple-office-hours-queue#115]
Don't know if this is intended, but if there are e.g. 2 open tickets and you click the "Assigned" tab, with e.g. 10 assigned, then the alerts count would read (10) instead of (2).

**Comment by MeshanKhosla** [comment]
Assuming you're talking about the page title, this is intended. The idea is that you can be on another page and still see the the tab you're on. It will keep the count of what you're currently looking at including any filters that you apply.
