### ISSUE TITLE
global and personal statistics are the same

### ISSUE THREAD

**Issue by kanavmittal314** [Berkeley-CS61B/simple-office-hours-queue#139]
In activity tab: 

<img width="1436" alt="image" src="https://github.com/Berkeley-CS61B/simple-office-hours-queue/assets/44180897/1c584f95-c3a6-4937-81b4-11733565c49d">

**Comment by MeshanKhosla** [comment]
FIxed https://github.com/Berkeley-CS61B/simple-office-hours-queue/commit/03e148b2c0c0296baffc145b4c6ffe13f64dac43
