### ISSUE TITLE
Add automatic expiring section for absentee tickets

### ISSUE THREAD

**Issue by noahadhikari** [Berkeley-CS61B/simple-office-hours-queue#34]
Currently the top of the OH queue gets flooded with students who aren't present when their name is called but still get requeued. It would be nice to have a separate section for absent students whose tickets expire after a set period of time, e.g. 5 minutes.

**Comment by laksith19** [comment]
Like a mark absent button from the TA perspective?

**Comment by MeshanKhosla** [comment]
> Like a mark absent button from the TA perspective?

Yes

**Comment by MeshanKhosla** [comment]
Done https://github.com/Berkeley-CS61B/simple-office-hours-queue/pull/36
