### ISSUE TITLE
Dev mode

### ISSUE THREAD

**Issue by antonzabreyko** [Berkeley-CS61B/simple-office-hours-queue#46]
It might make sense to have an additional role to student and staff, dev, that can take all actions on the website. In essence, it's basically a staff member that can also make tickets and serve as concierge. This would facilitate development and testing, both locally and on production.

**Comment by MeshanKhosla** [comment]
Yeah, we could do that. Also, it's worth noting that the only [UserRoles ](https://github.com/Berkeley-CS61B/simple-office-hours-queue/blob/main/prisma/schema.prisma#L176)that are actually mean anything right now are STUDENT, and STAFF. We could probably get rid of CONCIERGE and maybe turn ADMIN into the dev role you're talking about.

**Comment by MeshanKhosla** [comment]
https://github.com/Berkeley-CS61B/simple-office-hours-queue/pull/109 allows staff members to create tickets
