### ISSUE TITLE
Absent timer doesn't reset after unmarking

### ISSUE THREAD

**Issue by allengu01** [Berkeley-CS61B/simple-office-hours-queue#47]
Marking as absent, unmarking, then marking as absent again doesn't reset the timer (not sure if this is intended?)

**Comment by MeshanKhosla** [comment]
Interesting, it looks like the timer does reset but the UI doesn't get updated. So if you refresh then everything looks fine. I'll look into it

**Comment by MeshanKhosla** [comment]
Fixed! https://github.com/Berkeley-CS61B/simple-office-hours-queue/pull/50
