### ISSUE TITLE
Closing queue without clearing hides tickets

### ISSUE THREAD

**Issue by allengu01** [Berkeley-CS61B/simple-office-hours-queue#52]
I don't think closing the queue should hide the tickets on the queue because of situations where we close the queue before the end of OH because it's so backed up. In those cases, we're still going to be taking tickets from the queue, just not allowing new ones to be created.

**Comment by MeshanKhosla** [comment]
Good point. Is this something you think you can work on? It should be a fairly simple change where we don't return early in TicketQueue.tsx

**Comment by allengu01** [comment]
Yep, I'll give it a shot

**Comment by MeshanKhosla** [comment]
https://github.com/Berkeley-CS61B/simple-office-hours-queue/pull/57
