### ISSUE TITLE
Ticket priority for certain assignments

### ISSUE THREAD

**Issue by noahadhikari** [Berkeley-CS61B/simple-office-hours-queue#53]
This would be useful for prioritizing lab tickets in lab and setup issues in OH for example.

**Comment by MeshanKhosla** [comment]
I'm also planning on adding priority for certain tickets. That way there's two ways to get a priority ticket:
1. Make a ticket with a priority assignment (ie: Setup
2. Whoever the OH head is can assign certain tickets as priority (maybe it's a group ticket or an escalate ticket from an AI)

**Comment by MeshanKhosla** [comment]
Done https://github.com/Berkeley-CS61B/simple-office-hours-queue/pull/55
