### ISSUE TITLE
Archive locations and assignments

### ISSUE THREAD

**Issue by antonzabreyko** [Berkeley-CS61B/simple-office-hours-queue#59]
While it is perhaps not best practice to delete locations and assignments from the database, it would be good if they could be archived so that they don't show up on the admin dashboard.

**Comment by MeshanKhosla** [comment]
We have this, it's the eye icon next to the assignments:

https://user-images.githubusercontent.com/24885081/212503046-5100976e-2a7a-4cc6-94f6-e2a990693d3c.mp4

**Comment by antonzabreyko** [comment]
Noted!
