### ISSUE TITLE
Site is in Arabic??

### ISSUE THREAD

**Issue by noahadhikari** [Berkeley-CS61B/simple-office-hours-queue#61]
When you enter the site (on Chrome at least), it asks if I'd like to translate from Arabic to English.
![image](https://user-images.githubusercontent.com/23223417/212840212-bb3159f9-5c1e-491b-9020-bf98f04e80a3.png)

**Comment by MeshanKhosla** [comment]
Fixed. For some reason Chrome thinks `61B` is in Arabic so I changed it to `CS61B` lol
